package it.polimi.saefa.instancesmanager.domain;

public enum SimulationProfile {
    RANDOM,
    SLOW_INSTANCE_RANDOM_AVAILABILITY,
    SLOW_INSTANCE_HIGH_AVAILABILITY,
    SLOW_INSTANCE_LOW_AVAILABILITY,
    FAST_INSTANCE_RANDOM_AVAILABILITY,
    FAST_INSTANCE_HIGH_AVAILABILITY,
    FAST_INSTANCE_LOW_AVAILABILITY,
    MIDSPEED_INSTANCE_RANDOM_AVAILABILITY,
    RANDOMSPEED_INSTANCE_LOW_AVAILABILITY,
    RANDOMSPEED_INSTANCE_HIGH_AVAILABILITY
}
